<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRecipientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRecipientRepository extends EntityRepository
{
	public function createQueryBuilderWhenSearchingForCardRecipientsByCard($cardId, $dqlParams = array())
    {
        $queryBuilder = $this->createGenericQueryBuilder($dqlParams);

        $queryBuilder
            ->select('card_recipient')
            ->from('ProjectHello\CoreBundle\Entity\CardRecipient', 'card_recipient')
            ->where('card.id = :card_id')
            ->setParameter('card_id', $cardId);

        return $queryBuilder;
    }
}