<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRecipientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRecipientRepository extends EntityRepository
{
}