<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository
{
	public function createQueryBuilderWhenSearchingForCardsCreatedByUser($userId)
	{
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder
			->select('card')
			->from('ProjectHello\CoreBundle\Entity\Card', 'card')
			->where('card.creator = :creator')
			->setParameter('creator', $userId);

		return $queryBuilder;
	}

	public function createQueryBuilderWhenSearchingForCardsReceivedByUser($userId)
	{
		$queryBuilder = $this->getEntityManager()->createQueryBuilder();

		$queryBuilder
			->select('card')
			->from('ProjectHello\CoreBundle\Entity\CardRecipient', 'cardRecipient')
			->innerJoin('cardRecipient.card', 'card')
			->where('cardRecipient.recipient = :recipient')
			->setParameter('recipient', $userId);

		return $queryBuilder;
	}
}