<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardCreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardCreatorRepository extends EntityRepository
{
}