<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends AllEntityRepository
{
    public function createQueryBuilderWhenSearchingForCardsCreatedByUser($userId, $dqlParams = array())
    {
        $queryBuilder = $this->createGenericQueryBuilder($dqlParams);

        $queryBuilder
            ->select('card')
            ->from('ProjectHello\CoreBundle\Entity\Card', 'card')
            ->where('card.creator = :creator')
            ->setParameter('creator', $userId);

        return $queryBuilder;
    }

    public function createQueryBuilderWhenSearchingForCardsReceivedByUser($userId, $dqlParams = array())
    {
        $queryBuilder = $this->createGenericQueryBuilder($dqlParams);

        $conditions = array(
            $queryBuilder->expr()->eq('cardRecipient.recipient', ':recipient'),
            $queryBuilder->expr()->eq('cardRecipient.card', 'card'),
        );

        $queryBuilder
            ->add('select', 'card')
            ->add('from', 'ProjectHello\CoreBundle\Entity\CardRecipient cardRecipient, ProjectHello\CoreBundle\Entity\Card card')
            ->where(call_user_func_array(array($queryBuilder->expr(), 'andx'), $conditions))
            ->setParameter('recipient', $userId);

        return $queryBuilder;
    }
}