<?php

namespace ProjectHello\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends AllEntityRepository
{
    public function createQueryBuilderWhenSearchingForMessagesOfCard($cardId, $dqlParams = array())
    {
        $queryBuilder = $this->createGenericQueryBuilder($dqlParams);

        $queryBuilder
            ->select('message')
            ->from('ProjectHello\CoreBundle\Entity\Message', 'message')
            ->where('message.card = :card')
            ->setParameter('card', $cardId);

        return $queryBuilder;
    }
}