security:
    encoders:
        ProjectHello\CoreBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
            entity: { class: ProjectHello\CoreBundle\Entity\User, property: emailAddress }

    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }