parameters:
#    project_hello_core.example.class: ProjectHello\CoreBundle\Example

services:
    card_service:
        class: ProjectHello\CoreBundle\Services\CardService
        arguments: []

    message_author_service:
        class: ProjectHello\CoreBundle\Services\MessageAuthorService
        arguments: []

    message_service:
        class: ProjectHello\CoreBundle\Services\MessageService
        arguments: []

    token_service:
        class: ProjectHello\CoreBundle\Services\TokenGeneratorService
        arguments: []