parameters:
#    project_hello_core.example.class: ProjectHello\CoreBundle\Example

services:

    authentication_handler:
        class: ProjectHello\CoreBundle\Handler\AuthenticationHandler
        arguments: [@router, @security.context]
    
    card_service:
        class: ProjectHello\CoreBundle\Services\CardService
        arguments: []

    message_service:
        class: ProjectHello\CoreBundle\Services\MessageService
        arguments: []

    user_service:
        class: ProjectHello\CoreBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager]

    token_service:
        class: ProjectHello\CoreBundle\Services\TokenGeneratorService

    string_util:
        class: ProjectHello\CoreBundle\Services\StringUtility
    
    card_recipient_service:
        class:  ProjectHello\CoreBundle\Services\CardRecipientService
