parameters:
#    project_hello_core.example.class: ProjectHello\CoreBundle\Example

services:
    card_service:
        class: ProjectHello\CoreBundle\Services\CardService
        arguments: []

    message_service:
        class: ProjectHello\CoreBundle\Services\MessageService
        arguments: []

    user_service:
        class: ProjectHello\CoreBundle\Services\UserService
        arguments: [@doctrine.orm.entity_manager]

    token_service:
        class: ProjectHello\CoreBundle\Services\TokenGeneratorService