ProjectHello\CoreBundle\Entity\Message:
    properties:
        message:
            - NotBlank: ~

ProjectHello\CoreBundle\Entity\Card:
    properties:
        sendingDate:
            - NotBlank: ~
            - Type: \DateTime