create_card:
    pattern: /
    defaults: { _controller: ProjectHelloMainBundle:Default:createCard }

add_message:
    pattern: /add-message
    defaults: { _controller: ProjectHelloMainBundle:Default:addMessage }

view_card:
    pattern: /view-card
    defaults: { _controller: ProjectHelloMainBundle:Default:viewCard }