homepage:
    pattern: /
    defaults: { _controller: ProjectHelloMainBundle:Default:homepage }

dashboard:
    pattern: /dashboard
    defaults: { _controller: ProjectHelloMainBundle:Default:dashboard }


create_card:
    pattern: /create-card
    defaults: { _controller: ProjectHelloMainBundle:Default:createCard }

edit_card:
    pattern: /edit-card
    defaults: { _controller: ProjectHelloMainBundle:Default:editCard }

add_message:
    pattern: /add-message
    defaults: { _controller: ProjectHelloMainBundle:Default:addMessage }

guest_view_card:
    pattern: /guest-view-card
    defaults: { _controller: ProjectHelloMainBundle:Default:guestViewCard }

register:
    pattern: /register
    defaults: { _controller: ProjectHelloMainBundle:Default:registerUser }
    requirements:
        _method: POST

verify_account:
    pattern: /verify-account
    defaults: { _controller: ProjectHelloMainBundle:Default:verifyAccount }
    
login_check:
    pattern:  /login_check

logout:
    pattern:  /logout
