homepage:
    pattern: /
    defaults: { _controller: ProjectHelloMainBundle:Default:homepage }

dashboard:
    pattern: /dashboard
    defaults: { _controller: ProjectHelloMainBundle:Default:dashboard }


create_card:
    pattern: /create-card
    defaults: { _controller: ProjectHelloMainBundle:Default:createCard }

add_message:
    pattern: /add-message
    defaults: { _controller: ProjectHelloMainBundle:Default:addMessage }

view_card:
    pattern: /view-card/{card_id}
    defaults: { _controller: ProjectHelloMainBundle:Default:viewCard }

register:
    pattern: /register
    defaults: { _controller: ProjectHelloMainBundle:Default:registerUser }
    requirements:
        _method: POST

verify_account:
    pattern: /verify-account
    defaults: { _controller: ProjectHelloMainBundle:Default:verifyAccount }