ProjectHello\CoreBundle\Entity\Message:
    properties:
        message:
            - NotBlank: ~

ProjectHello\CoreBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        emailAddress:
            - NotBlank: ~